### ISSUE TITLE
Draco Minix 2.0

### ISSUE THREAD

**Issue by jean-loups** [dracolinux/DracoLinux#28]
hello,
i search a Linux for develop my skill in µ-kernel and particularly Minix 2.0 [3-Clause BSD licence, may be pass to GPL-v3]
after speak about on Ubuntu mailing list systemd isn´t a good way for my project.

i invited you to visit my repo : [https://github.com/jean-loups/Ubuntu-Minix-2.0](https://github.com/jean-loups/Ubuntu-Minix-2.0)
i would like develop for cortex A72 beagle board AI-64

may be joining our efforts
very best regard,
jean-loups white

**Comment by FabioLolix** [comment]
So @jean-loups the fork you are using by @Heitai-C11 is an hostile fork of Minix where the development history have been resetted and the License too, your fork too, the first thing [done](https://github.com/jean-loups/Ubuntu-Minix-2.0/commit/323990edfd9510f0df580e185b547e978c790384) is license washing, the BSD 3-Clause License ask only 3 things, the first is **"must retain the above copyright notice, this list of conditions and the following disclaimer"**, that very rude towards the developers

**Comment by jean-loups** [comment]
hi @FabioLolix can stay on 3-Clause License, Draco use pkgsrc in BSD License, but the real problem is the init system, Ubuntu use systemd, not compatible with Minix-2.0
conseil me to find an Linux use Init initialization system. Draco seem the BEST, because i test since some year and is greate

**Comment by FabioLolix** [comment]
> conseil me to find an Linux use Init initialization system

https://duckduckgo.com/?t=ffab&q=Linux+init+system&atb=v320-1&ia=web 

OpenRC, SysVinit, runit, S6, Dinit

**Comment by jean-loups** [comment]
Le 2023/07/01 00:10, Fabio Loli a écrit :
>> conseil me to find an Linux use Init initialization system
> 
> https://duckduckgo.com/?t=ffab&q=Linux+init+system&atb=v320-1&ia=web
> 
> OpenRC, SysVinit, runit, S6, Dinit
propably OpenRC --> https://www.slant.co/topics/4663/~linux-init-systems 
<--
i was ask on FreeBSD Hackers mailing list
--> 
https://lists.freebsd.org/archives/freebsd-hackers/2023-June/002349.html 
<--

**Comment by rodlie** [comment]
Don't know what this has to do with Draco... Anyway, Draco is EOL (since 2012ish), and this is just an archive of the last known source/scripts.
